### ISSUE TITLE
IRC Outdated and Connecting Issues

### ISSUE THREAD

**Issue by JustOneMoreBlock** [Kirollos/Rocket_kIRC#9]
Hello,

I'm using Slack for Team Management and it has an option for IRC Client Support which I would rather get the bot(s) working into a channel than telling staff "Go here and there." or assisting them with more than one setups.

Host: TeamName.irc.slack.com
User: cory
Pass: TeamName.SO33D9629cI78OUzevQ053pxO
(Not real information, similar)

The username is the account that has been registered.

kIRC-debug
http://pastebin.com/raw.php?i=vCEQHr9V

Rocket Log
http://pastebin.com/raw.php?i=UWxRxRe7

[8/17/2015 10:19:52 AM] [Warning] Current version: v1.6.5, Latest version on repository is v1.6.6.

Your first thought would be to say to "Upgrade", however the latest file has been downloaded from Rocket Foundation, Releases in your Github Repository and even re-compiled for a 1.6.6 version and the same error persists.

kIRC Config
http://pastebin.com/raw.php?i=D73w2YS6

Slack Points they maybe causing the issue.
http://i.imgur.com/dQWTGhK.png

There is no password to join channels, however there is password to authorize the account and I assume that's what the password option is for.

Any assist will be greatly appreciated.

Kind Regards,
Cory

**Comment by Kirollos** [comment]
I forgot to update the server version in the code, so it will keep saying you'll need to upgrade (I'll fix that soon).

Regarding your issue, the server needs the client to enter a server password, which I've never implemented to the code. I'll add that right now and release it.

**Comment by Kirollos** [comment]
@JustOneMoreBlock Can you please compile the latest commit on repository (https://github.com/Kirollos/Rocket_kIRC/commit/e2f129bdc3c8210440c96245991ddac571195cf9) and confirm if the issue was resolved? If you currently cannot compile it, I'll upload the binary for you.

**Comment by Kirollos** [comment]
Forgot to mention that you need to add your password (that is sent through /PASS) in the config.

``` xml
<spassword>EDITME</spassword>
```

**Comment by JustOneMoreBlock** [comment]
Compiled. :)

Works!

http://pastebin.com/raw.php?i=aqNg8EdB

http://i.imgur.com/UK5MICf.png

http://i.imgur.com/7I0f9sa.png

**Comment by Kirollos** [comment]
I'm sorry but I don't get what do you mean?

**Comment by JustOneMoreBlock** [comment]
Never mind. It wouldn't show and then your post you mentioned about the spassword thing. :P - So I removed it.

Seems to work, just need to figure out how to grant the voice for the bot.

**Comment by Kirollos** [comment]
Ah, cool!
I'm going to release this version right now, thank you :).

In standard IRC networks you need to use /mode [channel name] +v [nick].
